#!/usr/bin/ruby

require './lib/account'
require './lib/account_id_verification_process'
require './lib/value_verification_process'

SEPARATOR = ","

accounts_with_balance = {}
c = File.open("files/contas.csv")
t = File.open("files/transacoes.csv")

c.each do |line|
  id, initial_amount = line.split SEPARATOR

  if AccountIdVerificationProcess.process(id) && ValueVerificationProcess.process(initial_amount)
    accounts_with_balance[id] = Account.new(id, initial_amount)
  end
end

t.each do |line|
  id, transaction = line.split SEPARATOR

  if AccountIdVerificationProcess.process(id) && ValueVerificationProcess.process(transaction)
    accounts_with_balance[id].add_transaction transaction
  end
end

f = File.new("saldo.csv", "w")
accounts_with_balance.each do |id, account|
  f.write("#{id},#{account.balance}\n")
  puts "#{id},#{account.balance}"
end
f.close
